version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: devbase_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devbase
      POSTGRES_PASSWORD: devbase
      POSTGRES_DB: devbase
    volumes:
      - devbase_pgdata:/var/lib/postgresql/data

volumes:
  devbase_pgdata:
